# Generated by Django 5.2.11 on 2026-02-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(help_text='SHA-256 hash of the raw API key token; the plaintext is never stored.', max_length=64, unique=True),
        ),
    ]
