# Generated by Django 4.2.28 on 2026-02-22 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_apikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='files.apikey', verbose_name='API key'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('sha256_hash__isnull', False)), fields=('sha256_hash', 'api_key'), name='unique_hash_per_api_key'),
        ),
    ]
